name: Pull request check

on: [pull_request]

jobs:
  block-fixup-merge:
    runs-on: ubuntu-latest
    name: Block fixup commits

    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5

      - name: Block fixup commit merge
        uses: 13rac1/block-fixup-merge-action@bd5504fb9ca0253e109d98eb86b7debc01970cdc # v2.0.0
